### ISSUE TITLE
Feature: Message completion

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#101]
This is a feature suggestion.

Allow completing messages for symbols in the project.  Example:

```
foo::bar = "mess";
```

Now after `foo::` and triggering completion, it should suggest `bar`.

**Comment by szhorvat** [comment]
This should be of *lowest* priority.  It would be a useful feature, but not frequently used.

**Comment by halirutan** [comment]
It works already inside `Message[..]`. This feature is bound to *smart completion* which is `Ctrl`+`Shift`+`Space` on Linux. But I already thought about extending this and when I see it correctly, it should really be an easy fix.

**Comment by halirutan** [comment]
@szhorvat Could you comment on if Smart Enter that works inside `Message` is the main application and enough?

**Comment by szhorvat** [comment]
Yes, theoretically good enough. I need to keep it in mind and start triggering smart completion there.
