### ISSUE TITLE
Module Language Level is reset after every restart

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#106]
I am trying to set the Module Language Level to 10.0:

![image](https://user-images.githubusercontent.com/1212871/42366176-d89c51a0-8100-11e8-8d13-ecb8304599fb.png)

However, after restarting IDEA, it jumps back to 11.2.

I could reproduce this with two different projects.

**Comment by halirutan** [comment]
Fixed in the development tree.
