### ISSUE TITLE
Add symbols used in new style packages

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#109]
Leonid described new style packages [here](https://mathematica.stackexchange.com/a/176489/12). They use some special "symbol names". According to his description, these aren't really treated as symbols by the kernel (unless I got it wrong), but IDEA does see them as symbols.

IDEA should recognize them as built-in symbols.

They are (at least):

```
Package
PackageExport
PackageImport
PackageScope
```

**Comment by halirutan** [comment]
Done in beta
