### ISSUE TITLE
Cross-file refactoring is broken

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#111]
Suppose we are using a function called `fun1` in a file. `fun1` is defined in a different file. The IDEA recognizes it even in the file where we are using it because it has a usage message.

`fun1` is defined here:

![image](https://user-images.githubusercontent.com/1212871/47366894-e5b92500-d6de-11e8-8d84-4cdf5d489788.png)

We are using it here. It is underlined with a straight line, which means that it is a known function.

![image](https://user-images.githubusercontent.com/1212871/47366936-f49fd780-d6de-11e8-8bb7-42f0f1bdb802.png)

Now I right click `fun1` and choose Refactor -> Rename

![image](https://user-images.githubusercontent.com/1212871/47366980-0c775b80-d6df-11e8-947b-03b7558a4840.png)

The renaming worked in the file I was editing:

![image](https://user-images.githubusercontent.com/1212871/47367025-20bb5880-d6df-11e8-8e0c-bbbedc405055.png)

But in the other file, only the usage message was affected:

![image](https://user-images.githubusercontent.com/1212871/47367045-2add5700-d6df-11e8-81fe-e560a87fc154.png)

Now things are broken.

**Comment by halirutan** [comment]
I have to admit, I was aware of this. It is on my list :) Thanks for making an issue so that I don't forget it.

Btw, this really should not be broken at all because I don't take care of the renaming. What goes wrong is IDEA's search for all references that need to be renamed.

**Comment by halirutan** [comment]
Fixed in the latest beta
