### ISSUE TITLE
Color settings for DynamicModule and With

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Mathematica-IntelliJ-Plugin#114]
Can we have `WITH/DYNAMIC_MODULE_LOCALIZED` settings? 

By default they can be the same as `Module`.

Motivation: in context of gui programming there is a heavy mix of Module/With/DynamicModule and it would make it easier to read code.

**Comment by halirutan** [comment]
I cleaned up the whole situation and in the next version, it should be possible to adjust this (plus some more settings). Be aware that this update will definitely break existing color settings.

![img](http://i.imgur.com/cKjUxjx.png)
