### ISSUE TITLE
DynamicModule variables in Initialization

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Mathematica-IntelliJ-Plugin#116]
```DynamicModule[{x}, Dynamic[x], Initialization :> (x)]```

![image](https://user-images.githubusercontent.com/15227576/53671603-76040980-3c7f-11e9-8c97-4ba9660789c0.png)

It seems they are not captured as local which makes

- Syntax coloring off
- `x` in `Initialization` is marked with 'could not resolve symbol definition'

v3.0beta16

**Comment by halirutan** [comment]
Also applies to `Manipulate` which is atm not handled at all due to its obscure variety of possible variable forms.

**Comment by halirutan** [comment]
@kubaPod This should be fixed in the upcoming version. It currently only works for `DynamicModule` as I haven't sorted out the mess with all the different possibilities of `Manipulate`.
