### ISSUE TITLE
Minor installation issue regarding plugin name - IDEA calls it "Wolfram ..."

### ISSUE THREAD

**Issue by stub22** [halirutan/Mathematica-IntelliJ-Plugin#122]
README instructions for installation currently say:
" On the right side you find the button Browse repositories and there you use the search box to find the Mathematica Support."

However, using IDEA community edition 2018.3.5 (on MS-Windows 7, JDK 8), searching the plugin Marketplace for "Mathematica" revealed only an unrelated plugin called "Mathematica REPL".   (The GUI for repositories is somewhat different than when this README was
written, and possibly the plugin-name-display logic is different as well).  
 
We actually need to search for "Wolfram".  When we do that, the Mathematica-IntelliJ-Plugin shows up (called "Wolfram ______") and installs OK.  (I decided it was the right one because author name looked correct). 
Plot twist:  AFTER installation, it is called "Mathematica Support" in the list of plugins.  

Recommend updating the readme to tell users to search for "Wolfram" plugin.

**Comment by halirutan** [comment]
The *officially* available version of the plugin is outdated and very likely to show signs of a slow breakdown in newer IDEA versions. I am working on a new version of the plugin which will be called (similarly to IDEA) version 2019.x and as soon as the JetBrains Marketplace is ready, it will be available.

The new version is already available as a beta and you can follow the instructions here:

https://github.com/halirutan/Mathematica-IntelliJ-Plugin/wiki/Beta-Release

The renaming to "Wolfram Language" has two reasons: 1. Stephen Wolfram wanted to call the language after himself and forced this general rebranding for several years and 2. JetBrains also suggested a unification of plugin names which esp. means leaving out words like "support" and rather call the plugin like the programming language.

If you install the beta version, you will find that everything has been renamed to "Wolfram Language" including the plugin name itself.
