### ISSUE TITLE
Symbol with dollar in name not completed in Block

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#123]
In the following example, `$barbar` is not offered for auto-completion. `foofoo` works fine.

```mma
Block[{foofoo, $barbar},
  $bar 
]
```

**Comment by halirutan** [comment]
@szhorvat Yep, I'm not sure what the heck I was thinking, but the code responsible for the bug is from 2013. That might explain it. Most importantly, I found the exact place where the `$barbar` suggestion gets removed and I'm looking at it later when I'm back home.

**Comment by halirutan** [comment]
I believe this should be fixed now. This code was written exactly 6.2 years ago :)
