### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by minkir014** [halirutan/Mathematica-IntelliJ-Plugin#126]
Does this extension have a debugger?

**Comment by szhorvat** [comment]
No.

But I suggest reading this: https://mathematica.stackexchange.com/a/119962

**Comment by minkir014** [comment]
But the option `break at assert ` isn't available in Intellij idea. Or you suggest that I should use `Mathematica` itself for that.

**Comment by szhorvat** [comment]
I am not sure what you mean with the last comment.  The Wolfram Language plugin for IDEA does not have a debugger.

My point with the link was that you may not need a traditional, line-number based debugger. I use Mathematica's built-in debugger for projects that I edit with IDEA. I find it very convenient. But the workflow is a bit different (described in the linked post).

(Do not take this as a comment on whether a traditional debugger is useful or not, or whether the plugin should or shouldn't have one. I am not the one to make decisions about that.)

**Comment by minkir014** [comment]
Thanks for response.
