### ISSUE TITLE
์Not compatible with Intellij IDEA 2019

### ISSUE THREAD

**Issue by testn** [halirutan/Mathematica-IntelliJ-Plugin#127]
It does not seem to be compatible with Intellij IDEA 2019. Could you please help check?

**Comment by halirutan** [comment]
Currently, we are preparing the Wolfram Language Plugin 2019 for the official release. If you want to try the beta, please read here:

https://github.com/halirutan/Wolfram-Language-IntelliJ-Plugin-Archive/wiki/Beta-Release
