### ISSUE TITLE
Over eager 'suspicious pattern test' 

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Mathematica-IntelliJ-Plugin#131]
`_?Positive` in `Switch[#, _?Positive, #, _ 0]& @ 1` should not be highlighted.

![image](https://user-images.githubusercontent.com/15227576/63154150-4c158800-c010-11e9-9feb-b5783fd53542.png)

 - Windows I IDEA 2019.2 / plugin 2019.2.1.1

**Comment by halirutan** [comment]
I fixed this and made a small addition to the warning message which now shows the `PatternTest` how it *would* be evaluated. This probably makes it more clear to the user what exactly is wrong

![image](https://user-images.githubusercontent.com/511683/63219954-68830300-c17d-11e9-8b85-a42f61254320.png)
