### ISSUE TITLE
"Go To Declaration" for messages also picks up where the message appear in the RHS of a definition

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#133]
Sometimes I define a message attached to symbol `A` to have the same text as a similar message attached to symbol `B`. Here's an example:

```mma
foo::bar = "boo";

f[] := Message[foo::bar]

boo::bar = foo::bar;
```

If I now go to `Message[foo::bar]` and trigger "Go To Declaration", it will offer two hits. One is the actual definition of `foo::bar`, but the other one is a different definition in which `foo::bar` appears only on the RHS.

![image](https://user-images.githubusercontent.com/1212871/63216294-9cd1d180-c133-11e9-8fb9-1b40c03e360b.png)

----

I am not sure if you intended this. Probably not. In practice, this behaviour doesn't bother me at all, but it seemed worth reporting anyway.

**Comment by halirutan** [comment]
@szhorvat Thanks! Indeed, I didn't check if the `foo:bar` was on the LHS of the `=`.
