### ISSUE TITLE
Cannot resolve symbol definition inspection in a pattern inside Shortest 

### ISSUE THREAD

**Issue by gerli** [halirutan/Mathematica-IntelliJ-Plugin#138]
```
{1, 2, 3} /. {x__, Shortest[y__]} :> {{x}, {y}};
```
The `y` is not correctly detected as a named pattern (x is).

![Selection_1229](https://user-images.githubusercontent.com/6066719/66570036-6a61b500-eb75-11e9-8b99-c5fd989f4001.png)

**Comment by halirutan** [comment]
Fixed
