### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by atom-sun** [halirutan/Mathematica-IntelliJ-Plugin#144]
I'm a graduate student in physics and I'm also an active member of the Mathematica.SE community:

https://mathematica.stackexchange.com/users/29489/atoman

I'm planning to use the plugin in conjunction with the Free Wolfram Engine for Developers and IntelliJ softwares for doing calculation in scientific research. 

Some code using Wolfram language can be found here: https://github.com/atom-sun/chern

**Comment by halirutan** [comment]
Please send me a mail with your full name and the email address you used for your Jetbrains account to

```
Uncompress["1:eJxTTMoPChZhYGAoSCwpykzOdshIzMksKi1JzNNLSQUAgX0JmQ=="]
```

**Comment by atom-sun** [comment]
> Please send me a mail with your full name and the email address you used for your Jetbrains account to
> 
> ```
> Uncompress["1:eJxTTMoPChZhYGAoSCwpykzOdshIzMksKi1JzNNLSQUAgX0JmQ=="]
> ```

Sent.

**Comment by halirutan** [comment]
@atom-sun Granted. You should have received a mail with your license.
