### ISSUE TITLE
Module, Block, With all collapse.  CompoundExpression[...] should also collapse.

### ISSUE THREAD

**Issue by MrHirenP** [halirutan/Mathematica-IntelliJ-Plugin#147]
Some functions don't need any local variables.  For those, I use CompoundExpression[...] to group the code as in:

```
myFunction[expr_] :=
  CompoundExpression[
    statement1,
    statement2,
    statement3,
    output];
```

<img width="97" alt="With-collapse" src="https://user-images.githubusercontent.com/26680488/71549989-b570b480-297b-11ea-8377-6e084e216a4e.png">

<img width="182" alt="CompoundExpression-nocollapse" src="https://user-images.githubusercontent.com/26680488/71549985-ac7fe300-297b-11ea-8ed0-5b35e148669e.png">

Can you make CompoundExpression collapsable?

**Comment by halirutan** [comment]
Et voilà:

![img](http://i.imgur.com/GwpQbrH.png)

Available in the next [prerelease version](https://wlplugin.halirutan.de/docs/installation/#using-eap-beta-releases).
