### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by GiovanniBordiga** [halirutan/Mathematica-IntelliJ-Plugin#149]
Hi there! First of all, great plugin!

I'm a PhD student in solid mechanics working at the University of Trento, Italy. I use Mathematica and Wolfram Language regularly for research and teaching purposes. I'd like to apply for a free license of this plugin. 
Thank you.

**Comment by halirutan** [comment]
@GiovanniBordiga Sure! Did you already create [a Jetbrains account](https://account.jetbrains.com/login) with the university mail address that I see on GitHub?

**Comment by GiovanniBordiga** [comment]
@halirutan I created it now using the university mail address that you see on GitHub.

**Comment by halirutan** [comment]
@GiovanniBordiga Jetbrains can't find any accounts under your name. Can you login into your account, navigate at the top to "Your Account" and make a screenshot? Send it to my mail address and I'll forward it.

**Comment by GiovanniBordiga** [comment]
@halirutan I've sent you the screenshot. Thanks a lot for your time!
