### ISSUE TITLE
Symbols incorrectly offered from Global context during auto-completion

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#151]
When I explicitly trigger auto-completion, I get symbols in the Global context that should not be there.

Example:

Suppose we want ``Internal`NonNegativeMachineIntegerQ``. I often rely on auto-completion, because I can't remember which of these symbols is in which context (Developer, Internal, etc.)

Type `NagetiveMa` and press the shortcut for triggering completion. I see this:

![image](https://user-images.githubusercontent.com/1212871/74416503-83d97d00-4e45-11ea-8a98-b84d3569577a.png)

This is in a scratch buffer. Can you reproduce it?

 - OS: macOS
 - IntelliJ Product IntelliJ: 2019.3.3
 - Wolfram Plugin Version: 2019.3

**Comment by halirutan** [comment]
One important question is: How often did you press `Cmd`+`Space` before the global symbols appear? I have different "layers" of autocompletion and the more often you press it manually, the more things will appear in some contexts.

One suspicion I have is that you *used* `NegativeMachineIntegerQ` inside your file(s) and at some point, the autocompletion will suggest it because it will give you a list of all symbols you used (no matter if they make sense). And since I'm not determining contexts inside files, it gets the Global prefix.

This is only a guess on my side and I have to check when I'm home.

**Comment by szhorvat** [comment]
Firs I type `NonNegativeMa`, at which point there are no completions offered without asking for any explicitly. Then I use Code -> Completion -> Basic precisely once (I have different shortcuts assigned and I wanted to make sure that there is no mistake made, so I used the menu this time). Then I get this:

![image](https://user-images.githubusercontent.com/1212871/74428479-5bf41480-4e59-11ea-958d-d178c8207ab3.png)

This is now in a project where I did not use `NonNegativeMachineIntegerQ` at all (verified with `grep`).

If I complete it, it is coloured in blue:

![image](https://user-images.githubusercontent.com/1212871/74428544-88a82c00-4e59-11ea-8e1b-10e2ad45e786.png)

**Comment by halirutan** [comment]
Thanks! Let me have a look at this.

**Comment by halirutan** [comment]
@szhorvat The good news is that your specific issue was an oversight of me. I did not exclude the ``Global` `` context when scraping the kernel for all available symbols. The symbols are put in JSON files and used for autocompletion.

The scary part is that *something* polluted the global context when I did nothing more than accessing available symbols. Sure is that I never used `NonNegativeMachineIntegerQ` or any other of the about 100 symbols that made it into the global context.

I will include the fix in the next version, but I'll keep this issue open until I had a closer look at the created symbol and context lists.

**Comment by halirutan** [comment]
Btw, the source code that is used for gathering all information [is public](https://github.com/halirutan/Wolfram-IntelliJ-Tools/blob/master/IntelliJTools/IntelliJTools/IntelliJTools.m#L88-L98). Something like this

```wl
PacletDirectoryAdd["XXX/Wolfram-IntelliJ-Tools/IntelliJTools/IntelliJTools"];
<< IntelliJTools`
SaveCompleteMathematicaInformation["existing/directory"]
```

will create 5 JSON files under the specified directory with all information.
