### ISSUE TITLE
Incompatible with PyCharm 2019.3.2

### ISSUE THREAD

**Issue by shrubbroom** [halirutan/Mathematica-IntelliJ-Plugin#152]
Plugin incompatible with PyCharm 2019.3.2

I once used the plugin for development in older version of PyCharm, and it works well. However the plugin is incompatible with the current PyCharm verion after the last few updates and it shows that the plugin doesn't have a proper licence. I would be likely to code the .m script in PyCharm since I don't use Java so much as the Python. Could you help to check.

 - OS: Windows
 - PyCharm 2019.3.2
 - Wolfram Plugin Version 2019.2.3

**Comment by halirutan** [comment]
Since 2019, the Wolfram Language Plugin (WLP) is available through the Jetbrains Marketplace which means you need a paid or free license to use it. This step was necessary since the WLP had failed to become an open-source project with several developers working on it.

The reason why you could use it on PyCharm Community is that until the end of 2019, the licensing check was not implemented by Jetbrains for Community products. I decided to provide the WLP in an "extended trial" for all those products.

If you want to know the details, please read this blog post

https://wlplugin.halirutan.de/end-of-year-2019/

and check the licensing options on the website.

**Comment by shrubbroom** [comment]
Thanks for your kind and comprehensive reply.

I have applied the licence for students at [issue#142](https://github.com/halirutan/Wolfram-Language-IntelliJ-Plugin-Archive/issues/142), and it was successful. And I am currently using the professional version(version 2019.3.2, build PY-193.6015.41) but not the Community version of PyCharm.

However what's werid is that the plugin page shows that pulgin is neither licenced nor compatible with my PyCharm, which is unexpected since I think I have got the proper licence and the PyCharm pro will do the licence check correctly.

![pyc](https://user-images.githubusercontent.com/49093544/74904674-56fa0c80-53e7-11ea-8b6a-582ebfbfdcfe.JPG)

It will be kind of you to help to figure out the problem. Regards.

**Comment by shrubbroom** [comment]
Sorry for that disturbing. I have my plugin work correctly after I reinstall it. I am currently using the PyCharm professional and have a student licence. Weird that it shows the plugin is neither compatible nor licensed before the reinstalling. Everything goes well now. Thanks for your kind reply. Besides, this is really a fancy plugin.

**Comment by halirutan** [comment]
@shrubbroom One possible explanation is that you tested on PyCharm 2020 EAP. Is this possible? At the moment, the plugin is not compatible with the new 2020 versions, but I've fixed almost all issues and I will release a new plugin version soon. This will for testing only be available in the *beta* channel and you can [read here](https://wlplugin.halirutan.de/docs/installation/#using-eap-beta-releases) how to get these updates.

I'm not sure how this works with the license though and if you have to re-apply for the 2020 versions. But surely you can just try it out and give feedback.

**Comment by shrubbroom** [comment]
However I am now on the stable release by not the EAP version with PyCharm. And the problem occurs since the last update. From my perspective, this may be a probelm of PyCharm's auto-update for plugins since only after I manually install the Wolfram Language from the market again did the PyCharm get the correct compatible version. In one word, reinstall should be the first try to fix such kind of problem.

**Comment by halirutan** [comment]
@shrubbroom Another user could reproduce the problem. If it occurs again, please report back here and I'll investigate with Jetbrains why this happens. Thanks for the report!
