### ISSUE TITLE
Awkward green highlighting in autocompletion

### ISSUE THREAD

**Issue by halirutan** [halirutan/Mathematica-IntelliJ-Plugin#157]
Autocompletion popup in light mode shows an ugly green color. It's not coming from the WL Plugin, but maybe I can do something about it:

![image (1)](https://user-images.githubusercontent.com/511683/77614729-f1d98f80-6f2d-11ea-9ff0-2e2bd80ad334.png)

**Comment by halirutan** [comment]
@szhorvat I can't reproduce it on my side. Do you still see this issue?

**Comment by szhorvat** [comment]
Must have been an EAP issue. I cannot reproduce it either. Please close it.

**Comment by halirutan** [comment]
Good
