### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by ashotgasparyan** [halirutan/Mathematica-IntelliJ-Plugin#164]
To get a free license, I need some information. In the issue description, please provide information about how you want to use the plugin:

2. I am using Wolfram Mathematica in my research at Ruhr University Bochum, Germany.
https://inspirehep.net/authors/1072613#with-citation-summary

From this information, it must become clear that you are [eligible to obtain a free license](https://www.jetbrains.com/store/?fromNavMenu#discounts?billing=yearly). Furthermore, I need

- Your full name
Ashot Gasparyan

- The email address that you use in your Jetbrains account
ashot.gasparyan@rub.de

**Comment by halirutan** [comment]
You should have received your free license.
