### ISSUE TITLE
Associations or comments don't currently allow collapsing

### ISSUE THREAD

**Issue by gerli** [halirutan/Mathematica-IntelliJ-Plugin#165]
Out of these three constructions, lists can be collapsed:
```
{
    "x" -> 1
};

<|
    "x" -> 1
|>;

(*
    "x" -> 1
*)
```

![Selection_534](https://user-images.githubusercontent.com/6066719/84993372-e626ef00-b151-11ea-8842-0b7eb1ad176f.png)

It would be nice if associations and multiline comments could also be collapsible.

**Comment by halirutan** [comment]
In the next version, Associations will be foldable. Regarding comments, "sectioning comments" are already foldable and I'd like to leave it like that. So what you can do is structure your code into logical sections with these stylized comments. The advantage of that this approach is that your package files will look great when you open them in Mathematica. Please see the documentation here:

- [Folding section comments](https://wlplugin.halirutan.de/docs/code-folding/#folding-section-comments)
