### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by noshita** [halirutan/Mathematica-IntelliJ-Plugin#167]
To get a free license, I need some information. In the issue description, please provide information about how you want to use the plugin:

2. Information about academic or class-room usage
I use Wolfram Mathematica in my research projects at Kyushu University, Japan.

[Google scholar](https://scholar.google.com/citations?user=C3TzEA4AAAAJ)

From this information, it must become clear that you are [eligible to obtain a free license](https://www.jetbrains.com/store/?fromNavMenu#discounts?billing=yearly). Furthermore, I need

- Full name: Koji Noshita
- Email address: noshita@bio-math10.biology.kyushu-u.ac.jp

**Comment by halirutan** [comment]
I sent you a mail with the license
