### ISSUE TITLE
<-> oprator is not supported

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#17]
`a <-> b` is equivalent to `UndirectedEdge[a, b]`.  This syntax is not supported by the plugin.

![image](https://cloud.githubusercontent.com/assets/1212871/10412103/ae85d146-6f7b-11e5-831e-c4becc6b1d47.png)

**Comment by halirutan** [comment]
Fixed by [version 1.3](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/releases/tag/v1.3)
