### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by ChristopherMathematica** [halirutan/Mathematica-IntelliJ-Plugin#171]
To get a free license, I need some information. In the issue description, please provide information about how you want to use the plugin:
I go to a community college and I wanna build an app that teaches math for k-12.

1. Links to open-source projects
(I currently don't have any project links, but my github is ChristopherMathematica). I messaged you about this app before but fore some reason I can't find the email you giving me permissions.
2. Information about academic or class-room usage: I go to a community college and I want to learn more about different software packages. I am impressed with this project and I would like to use this.

From this information, it must become clear that you are [eligible to obtain a free license](https://www.jetbrains.com/store/?fromNavMenu#discounts?billing=yearly). Furthermore, I need

- Your full name: Christopher Yoenk
- The email address that you use in your Jetbrains account: sidesee3838@hotmail.com

You can send this sensitive information to the following email address if you don't feel comfortable putting them online:

```
Uncompress["1:eJxTTMoPChZhYGAoSCwpykzOdshIzMksKi1JzNNLSQUAgX0JmQ=="]
```

**Comment by halirutan** [comment]
Hey Christopher,

> I messaged you about this app before but fore some reason I can't find the email you giving me permissions.

I can't find any email either. Please write me a mail to the address that you get when you evaluate

```
Uncompress["1:eJxTTMoPChZhYGAoSCwpykzOdshIzMksKi1JzNNLSQUAgX0JmQ=="]
```

in Mathematica. I need some verification that you are actively enrolled in a college/school/university. That might be a website with your name on it or some scanned document.

**Comment by ChristopherMathematica** [comment]
Could you remove my name after its finished. I am not sure if I want my name and school online but this is proof
![proof](https://user-images.githubusercontent.com/58499404/89375961-d2612900-d6bc-11ea-8311-9fe303b7f5eb.JPG)

**Comment by halirutan** [comment]
OK, got it. I'll send you an email.
