### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by simonkeys** [halirutan/Mathematica-IntelliJ-Plugin#172]
I use the WL plugin for developing the open source AtomicDensityMatrix package: http://rochesterscientific.com/ADM/

It's been really helpful! I would appreciate a free license if you think it is appropriate.

Simon Rochester
simon.rochester@gmail.com

**Comment by halirutan** [comment]
That is a nice looking package page and I gladly provide a free license for you. I already sent you an email to the Gmail address with the necessary information.

**Comment by simonkeys** [comment]
Great, thanks so much!
