### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by subhodipbiswas** [halirutan/Mathematica-IntelliJ-Plugin#174]
To get a free license, I need some information. In the issue description, please provide information about how you want to use the plugin:

1. https://github.com/subhodipbiswas?tab=repositories
2. For optimization-based research involving real-world problems

From this information, it must become clear that you are [eligible to obtain a free license](https://www.jetbrains.com/store/?fromNavMenu#discounts?billing=yearly). Furthermore, I need

- Subhodip Biswas
- subhodip@cs.vt.edu

You can send this sensitive information to the following email address if you don't feel comfortable putting them online:

```
Uncompress["1:eJxTTMoPChZhYGAoSCwpykzOdshIzMksKi1JzNNLSQUAgX0JmQ=="]
```

**Comment by halirutan** [comment]
I sent you a mail with the license details. If something doesn't work out, feel free to contact me :)
