### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by HydrogenDeuterium** [halirutan/Mathematica-IntelliJ-Plugin#175]
​To get a free license, I need some information. In the issue description, please provide information about how you want to use the plugin:

2. Information about academic or class-room usage
I believe a email address that including edu is enough

From this information, it must become clear that you are [eligible to obtain a free license](https://www.jetbrains.com/store/?fromNavMenu#discounts?billing=yearly). Furthermore, I need

- Your full name
- The email address that you use in your Jetbrains account

Information has send to de address from my education email address.
```
Uncompress["1:eJxTTMoPChZhYGAoSCwpykzOdshIzMksKi1JzNNLSQUAgX0JmQ=="]
```

**Comment by halirutan** [comment]
@HydrogenDeuterium The above text is only the "template" text that you need to replace. Please provide all information as stated in the text.

**Comment by halirutan** [comment]
I believe this is the same person I granted a free license through mail communication.
