### ISSUE TITLE
Incompatibility with IntelliJ IDEA CE 2020.3

### ISSUE THREAD

**Issue by GiovanniBordiga** [halirutan/Mathematica-IntelliJ-Plugin#176]
Hello!
This morning, I found a problem similar to #170.

**Bug description**
Looks like the plugin is incompatible with the latest version of IntelliJ IDEA CE 2020.3.
At launch, the following error message appears

```
Plugin error: Plugin 'Wolfram Language' (version '2020.2') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IC-203.5981.155
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Update to IntelliJ IDEA CE 2020.3
2. Launch IntelliJ IDEA

**Expected behaviour**
Plugin should be compatible with IntelliJ IDEA 2020.3.

**Versions:**
 - OS: Ubuntu 18.04
 - IntelliJ IDEA 2020.3 (Community Edition) Build #IC-203.5981.155
 - Wolfram Plugin Version 2020.2

Hope this is helpful. Thanks!

**Comment by halirutan** [comment]
Hey @GiovanniBordiga, the WL Plugin is currently only available as beta for the 2020.3 version. [Check here](https://wlplugin.halirutan.de/docs/installation/#using-eap-beta-releases) how you can add the beta plugin channel in IDEA.

I will release it soon officially, but I need to be at least somewhat certain that no computers are exploding with the new version.

**Comment by GiovanniBordiga** [comment]
Gotcha, thanks!

**Comment by szhorvat** [comment]
This can be closed?

**Comment by GiovanniBordiga** [comment]
> This can be closed?

Yep!
