### ISSUE TITLE
Wishlist: Structured selection expansion

### ISSUE THREAD

**Issue by JonMcLoone** [halirutan/Mathematica-IntelliJ-Plugin#177]
Only feature I miss, so far moving from Eclipse....

Grow the selection using multiple clicks (ideally) or keystroke, in a Mathematica-valid and precidence respecting way.

eg Multiclick  on b in  Total[{1,Sin[abc]}]
1 click cusor inserted
2 clicks abc selected
3 clicks Sin[abc] selected
4 {1,Sin[abc]} selected
5 whole expression selected

Right now the first two clicks give the same behavior, but the third selects the line, and 4+ have no effect, even if the line is within a larger expression.

**Comment by szhorvat** [comment]
Just in case you were not aware of the keyboard shortcut for this: Option-Up does it on macOS. (I'm not sure if it's possible with mouse clicks.)

EDIT: It's in Edit -> Extend Selection. You can check what is the shortcut key on your system in the menu.

**Comment by kubaPod** [comment]
On Windows this unfortunately is <kbd>Ctrl</kbd>+<kbd>w</kbd>, RIP countless notebooks after switching to the FrontEnd :)

**Comment by JonMcLoone** [comment]
Closing as RTM - thanks

**Comment by szhorvat** [comment]
> On Windows this unfortunately is Ctrl+w, RIP countless notebooks after switching to the FrontEnd :)

Ctrl-W is a weird choice, as it's a standard shortcut to close windows ...

You can reconfigure it to be Ctrl-. to be consistent with Mathematica.
