### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by BriceLecampion** [halirutan/Mathematica-IntelliJ-Plugin#178]
Hello,

I am a faculty at EPFL and am developing with the Wofram language both for research and also use it at the doctorate level for graduate courses.

Would it be possible to have a free license of the Wolfram Language Plugin ?

Name: Brice Lecampion
email address of my jet brains account : brice .lecampion@epfl.ch 

Thanks a lot in advance
Prof. Brice Lecampion

**Comment by halirutan** [comment]
Hey Brice,

I sent you an email with the license code.

**Comment by BriceLecampion** [comment]
Thanks ! 
that’s great
brice
