### ISSUE TITLE
greek letter in comment

### ISSUE THREAD

**Issue by xslittlegrass** [halirutan/Mathematica-IntelliJ-Plugin#18]
It looks like that "Collapse all [Name] sections" works for greek letters in the usage message but not for greek letters in the comments. 

For example:

![snip20151012_4](https://cloud.githubusercontent.com/assets/2780075/10430929/8a7ff216-70c7-11e5-85f1-35280de4fc08.png)

**Comment by halirutan** [comment]
Fixed in the development version. I have put the foldable named characters into a so-called folding-group which means they always expand/collapse all if you open/close one. If this turns out to be more annoying than helpful, I'm instantiating the old behaviour.
