### ISSUE TITLE
IntelliJ 2021 compatibility

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#181]
IntelliJ 2021.1 is out and it would be nice to have a compatible beta version of the WL plugin.

**Comment by halirutan** [comment]
It's ready and I planned to release it this weekend.

**Comment by szhorvat** [comment]
You can ping this issue when the beta is out?

**Comment by halirutan** [comment]
I pushed it last night to the main repo, so everyone will get the update.

**Comment by szhorvat** [comment]
Was the "What's New" box removed? I can't find it in the menu anymore.

**Comment by halirutan** [comment]
Yes, as it was basically a repetition of the changelog that you can see in the IDE when you go to **Settings | Plugins | Wolfram Language** and check the description at the bottom. The changelog is also updated [on the Marketplace website](https://plugins.jetbrains.com/plugin/7232-wolfram-language). You should have seen a notification balloon with a clickable link to the changes though. But maybe you dismissed that as noise.

The good thing is that everything happens automatically and I only have to add to the changelog. Also, it doesn't annoy the users with a dialog that needs closing. I try to go along with the general philosophy of IntelliJ here.
