### ISSUE TITLE
Nested With statements cause incorrect error highlighting

### ISSUE THREAD

**Issue by JonMcLoone** [halirutan/Mathematica-IntelliJ-Plugin#182]
Code of the form
With[{a=1},With[{b=a},{a,b}]];
underlines the second "a" with an "Unused local variable" warning.

**Comment by halirutan** [comment]
To my shame, I'm already aware of this issue for a long time (https://github.com/halirutan/Wolfram-Language-IntelliJ-Plugin-Archive/issues/139). It's not as trivial to fix as I thought but it's on my pain list.
