### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by TihiyTi** [halirutan/Mathematica-IntelliJ-Plugin#183]
Hello,

I am a faculty at Bauman Moscow Technical University at the Faculty of Biomedical Technologies, and use Wolfram Mathematica and Wolfram Plugin for calculations in my research and teaching.

Can the free license for the Wolfram Language Plugin be renewed? I already received a license a year earlier.

Name: Alexey Tikhomirov
email address of my jet brains account : tikhomirov.an@bmstu.ru

Thanks a lot, Alexey

**Comment by halirutan** [comment]
I sent you a mail with the license details.
