### ISSUE TITLE
"Quick Documentation" feature displays my documentation, fails to display Wolfram's documentation.

### ISSUE THREAD

**Issue by siegenth** [halirutan/Mathematica-IntelliJ-Plugin#185]
**Describe the bug**

Placing cursor on a Wolfram function (ie ToUpperCase[]) and invoking 'Quick Documentation' should bring up function documentation - it does not.

If I put the cursor over a  function I created and invoke 'Quick Documentation' my documentation is displayed. 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...' Bring up Intellij.
2. Open '....'  Wolfram .ml file
3. place cursor over WL function (ie BeginPackage)
4. Open Menu : View | Quick Documentation
**Expected behaviour**
The Documentation pane opens, "Documentation: BeginPackage" appears in the title bar.
The documentation appears in the pane. 

**What I see**
The Documentation pane opens, "Documentation: BeginPackage" appears in the title bar.
The pane has "No documentation found".

** Screenshot**
![bug](https://user-images.githubusercontent.com/3303300/126242015-94f3174d-60da-4b85-b434-014b84d6816a.png)

**Please also provide:**
 - OS: [e.g. Mac OS X, Linux, Windows] - Mac OS Big Sur 11.4
 - IntelliJ Product [e.g. PyCharm 2019.1.3]  -IntelliJ IDEA 2021.3
 - Wolfram Plugin Version [e.g. 2019.2]  - 2021.1

**Comment by halirutan** [comment]
I believe to have identified the issue. It had nothing to do with the plugin but only that I use a CI for packaging and deploying it. In this step, the docs were missing.

I added unit tests for the docs (which are also run on the CI) for both Linux and macOS to be sure the docs are included in the build. Please use plugin version 2022.1.
