### ISSUE TITLE
12.3 NeuralNetwork` symbols are out of date.

### ISSUE THREAD

**Issue by alecGraves** [halirutan/Mathematica-IntelliJ-Plugin#187]
**Is your feature request related to a problem? Please describe.**
Some of the symbols (specifically within the NeuralNetwork` package) are out of date. Some newer symbols are missing in autocomplete, and some old symbols should be removed.

**Describe the solution you'd like**
Could you regenerate symbol info for Wolfram Language 12.3 updates? I am not sure exactly how your plugin works, but it seems like you probably have some automated process for this. 

Thank you! I really love your plugin; it is definitely the best way to modify WL code that I have ever used. I see there is another open issue to fix the documentation links, so when that is done, maybe you could check to make sure all the symbols are up-to-date?

**Comment by halirutan** [comment]
I already downloaded the official versions 12.2 and 12.3 and the plan is to include both versions because the symbols are also used in the "Is this function available for my Mathematica version" inspection.

**Comment by halirutan** [comment]
I'm closing this issue. I updated symbols, contexts and usage messages for Mathematica versions 12.2, 12.3 and 13.0. These changes will be part of the next release.

Here for instance is `NetArray` and `NetArrayLayer` which weren't included before:

![image](https://user-images.githubusercontent.com/511683/168473509-b0fd6abc-bea4-4884-9087-5b143a13f31f.png)
