### ISSUE TITLE
Intellij 2021.2 Support

### ISSUE THREAD

**Issue by alecGraves** [halirutan/Mathematica-IntelliJ-Plugin#188]
**Is your feature request related to a problem? Please describe.**
The plugin will not install on IntelliJ 2021.2 because it requires a previous IntelliJ build.

**Comment by halirutan** [comment]
Please try to install the beta build. See https://wlplugin.halirutan.de/docs/installation/#using-eap-beta-releases

At least for the next days, I'll want to see if some things got broken that weren't caught by the unit-tests before I push it to the main plugin repository.

**Comment by olivergrasl** [comment]
hi patrick - when is the update coming ... it would great to have a non-beta version soon.

**Comment by halirutan** [comment]
A new version that works for IntelliJ 2022.1 EAP is now available.
