### ISSUE TITLE
Plugin not found in Marketplace

### ISSUE THREAD

**Issue by introtp** [halirutan/Mathematica-IntelliJ-Plugin#192]
**Describe the bug**
Plugin not found in Marketplace

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings, Plugins, Marketplace 
2. Search for "Wolfram Language"
3. No plugin found

**Expected behaviour**
To find Wolfram Language plugin to install

**Screenshots**
Attached

**Please also provide:**
 - OS: Windows 10, OS Build: 19042.1348
 - IntelliJ Product 
PyCharm 2021.2.3 (Professional Edition)
Build #PY-212.5457.59, built on October 19, 2021
![Screenshot 2021-11-30 131153](https://user-images.githubusercontent.com/55222496/144053910-2f121bf8-95b6-4402-8af5-4850121460ca.png)

Licensed to XXXXXXXXXXX
You have a perpetual fallback license for this version.
Subscription is active until October 17, 2022.
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2038M
Cores: 8
Non-Bundled Plugins: Batch Scripts Support (1.0.12)

**Comment by introtp** [comment]
Reported the bug with Jetbrains on Youtrack as well

"PY-51859 Wolram Language plugin not available in Marketplace"
https://youtrack.jetbrains.com/issue/PY-51859

**Comment by halirutan** [comment]
Please try again. Version 2021.3 is released now.

**Comment by introtp** [comment]
Thanks for the prompt response now fixed. Will close the issue at Jetbrains too
