### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by PeterCullenBurbery** [halirutan/Mathematica-IntelliJ-Plugin#194]
The program's features in the following areas are not working (i.e., nothing happens):
autocompletion with Ctrl+Enter+Space
documentation lookup with Ctrl+Q
The last update was 2021.1 and Jetbrains IntelliJ IDEA Ultimate is now in 2022.1 EAP so I think somewhere compatability broke.

**Comment by halirutan** [comment]
The version released today works for 2022.1 EAP
