### ISSUE TITLE
'Could not resolve symbol definition' despite including ::usage 

### ISSUE THREAD

**Issue by Dollar4063** [halirutan/Mathematica-IntelliJ-Plugin#196]
**Describe the bug**
Getting an error message "Could not resolve symbol definition" despite including a ::usage message for that function

**To Reproduce**
1. Create a new project. In one file (called 'usageHere.m') write:

(************************)
Package["TestPackage`"]

PackageExport["ProblemFunction"]
ProblemFunction::usage="This is a function with a usage message";
ProblemFunction[x_]:=x+1;

PackageExport["foo"]
foo::usage="This function can resolve";
foo[x_]:=ProblemFunction[x]+2;
(************************)

2. In a second file, 'problemHere.m'
(************************)
Package["TestPackage`"]

PackageExport["Bar"]
Bar::usage = "This function could NOT resolve";
Bar[x_] := ProblemFunction[x] * 3;
(************************)

**Expected behaviour**
"ProblemFunction" should not have an error in 'problemHere.m'

**Screenshots**
![image](https://user-images.githubusercontent.com/124224477/219283564-5db277fc-35aa-4a6a-bd29-2961df525f74.png)

**Please also provide:**
 - OS: Windows
 - PyCharm 2022.3.1 (Professional Edition)
 - Wolfram Plugin Version 2022.3

**Comment by Dollar4063** [comment]
Updated to PyCharm 2022.3.2 (Professional Edition) and issue still persists

**Comment by halirutan** [comment]
To make resolution, navigation, autocompletion, etc across files work, the IDE has to have a notion of "what files belong together". In IntelliJ IDEA, unlike Python, there are [modules](https://www.jetbrains.com/help/idea/creating-and-managing-modules.html) and I documented [here](https://wlplugin.halirutan.de/docs/projects-modules/) how this is used to basically tell the IDE that it should look for definitions in all Wolfram files under a module.

In PyCharm, modules don't exist. However, what you can do is create a directory where you put your Wolfram files and [mark the directory as source](https://www.jetbrains.com/help/pycharm/configuring-project-structure.html#mark-dir-project-view). Then the IDE should recognize the definitions in the other files

![image](https://user-images.githubusercontent.com/511683/219825819-1c0f6f3e-641d-462c-9805-39000a1ee525.png)

**Comment by Dollar4063** [comment]
Thanks, that has fixed it!

Can I add definitions from other packages (eg "MongoCollectionCount" from "MongoLink`") in PyCharm?

**Comment by Dollar4063** [comment]
I will close this and open a new issue for the MongoLink question
