### ISSUE TITLE
"Could not resolve symbol definition" for built-in Wolfram libraries

### ISSUE THREAD

**Issue by Dollar4063** [halirutan/Mathematica-IntelliJ-Plugin#197]
**Describe the bug**
Symbols for built-in Wolfram libraries such as MongoLink` and ComputerArithmetic` are not recognised.

**To Reproduce**
Steps to reproduce the behaviour:

Type the following into a new file and "MongoCollectionFind" will not be recognised

==============================
PackageImport["MongoLink`"]

PackageExport["Bar"]
Bar::usage="bar use";
Bar[collection_, reportName_String] :=
    MongoCollectionFind[
      collection,
      <|"ReportName" -> reportName|>,
      <|"PricingDate" -> 1, "_id" -> 0|>
    ];
==============================

**Expected behaviour**
"MongoCollectionFind" should be recognised as a built-in function

**Screenshots**
![image](https://user-images.githubusercontent.com/124224477/222034657-c202860d-fcae-4d68-8c29-3af366e2634f.png)

**Please also provide:**
 - OS: Windows 10
 - PyCharm 2022.3.2 (Professional Edition)
 - Wolfram Plugin Version 2022.3

**Comment by szhorvat** [comment]
You can add these the same way as you'd add any other dependency. Then they will be scanned and their symbols recognized.

This is in contrast to truly built-in symbols for which there are no package files with accessible source code, so the only way to support their symbols is to hard-code them into the WL plugin

Use ``FindFile["MongoLink`"]`` to figure out where the package is located.

**Comment by Dollar4063** [comment]
Amazing! Thank you. I used FindFile["MongoLink`"] and added this as Source under my ProjectStructure
