### ISSUE TITLE
Plugin Wolfram Language (version 2024.2.1) is not compatible with the current version of the IDE (243.x)

### ISSUE THREAD

**Issue by davidpistachio** [halirutan/Mathematica-IntelliJ-Plugin#201]
**Describe the bug**
The plugin does not appear to be compatible with the latest versions of JetBrains IDEs (v243.x)

This occurs when the plugin is already installed, but the easiest way to reproduce it is to attempt a manual installation.

**To Reproduce**
Steps to reproduce the behaviour:
1. Update your IDE (e.g. PyCharm)
2. Go to https://plugins.jetbrains.com/plugin/7232-wolfram-language/versions/stable
3. Download plugin version 2024.2.1
3. In the IDE, attempt a manual installation

**Expected behaviour**
The plugin should install without error. Wolfram files should be recognised as usual.

**Error messages**

```
Plugin 'Wolfram Language' (version '2024.2.1') is not compatible with the current version of the IDE, because it requires build 242.* or older but the current build is PY-243.21565.199
```

```
Plugin 'Wolfram Language' (version '2024.2.1') is not compatible with the current version of the IDE, because it requires build 242.* or older but the current build is GO-243.21565.208
```

```
Plugin 'Wolfram Language' (version '2024.2.1’) is not compatible with the current version of the IDE, because it requires build 242.* or older but the current build is RR-243.21565.245
```

**Please also provide:**
 - OS: macOS
 - IntelliJ Product: PyCharm Professional 2024.3 build PY-243.21565.199 (and other products too)
 - Wolfram Plugin Version: 2024.2.1

**Comment by carlobarbieri** [comment]
I've been struggling with this for a couple of weeks now, there isn't anything in the beta channel either.

**Comment by halirutan** [comment]
Official release support 243 is out now
