### ISSUE TITLE
Feature suggestion: Collapsing subscripts

### ISSUE THREAD

**Issue by alpha358** [halirutan/Mathematica-IntelliJ-Plugin#29]
Is it possible to make subscripts collapse ?
For example: 
`\!\(\*SubscriptBox[\(\[Phi]\), \({a, b}\)]\)`
![image](https://cloud.githubusercontent.com/assets/17505314/13775646/61d73c32-eaae-11e5-972f-1c72484904b3.png)

**Comment by szhorvat** [comment]
What would you expect it to collapse to?  A display like this?

![image](https://cloud.githubusercontent.com/assets/1212871/13775653/0b27645a-eaa6-11e5-8ad4-b853a72e59ae.png)

That would involve having to display special formatting which may not play well with the rendering of text with fixed-width characters.

There is also another issue here.  What is it that you want to collapse?  `Subscript[\[Phi], {a, b}]` or `\!\(\*SubscriptBox[\(\[Phi]\), \({a, b}\)]\)`?  These two are not the same thing.  The former is a simple Mathematica expression.  The latter is a box representation of that expression used by the front end.  These boxes can be denotes using Mathematica expressions like this:

    SubscriptBox["\[Phi]", RowBox[{"{", RowBox[{"a", ",", "b"}], "}"}]]

Or using a special string-based syntax like this:

    \!\(\*SubscriptBox[\(\[Phi]\), \({a, b}\)]\)

http://reference.wolfram.com/language/tutorial/StringRepresentationOfBoxes.html

Ultimately, using boxes (which are really Front End stuff) _to denote code_ in a plain-text package does not seem like such a good idea.

The one exception is in usage message, where this sort of stuff can be quite useful.

But creating a new parser to handle the string representation of boxes seems like a lot of work for relatively little gain...

Of course it's up to @halirutan to decide what to implement, but as another IDEA user I would vote to spend time on projects with a higher return...

**Comment by szhorvat** [comment]
I'm wondering if it would be possible to have strings like this rendered by Mathematica itself (when the plugin gets good Mathematica integration) and display them as a tooltip or similar.

I'm thinking of how [preview-latex work within Emacs](https://www.gnu.org/software/auctex/preview-latex.html).  The formulas can be shown in graphical rendered form or editable textual form.

It still seems like a large project so it's a question whether it is worth the effort.

**Comment by halirutan** [comment]
@szhorvat described the situation pretty well. Box-Expressions are not supported by the plugin and although it seems like a minor thing to support folding of things like subscripts it's not. The box representation as it is used by the front end needs to be parsed separately as it is not simple Mathematica code.

However, the important point is that the plugin is not meant to compete with the front end or reproduce its functionality. It is meant as development environment for packages or plain code. The only contact point between plugin and front end is that in recent versions the normal usage messages of functions have evolved into a more stylish thing which uses a lot of typesetting.

The underlying *string-based box representation* is ugly. No one ever is going to type six million backslashes. Let me give you an example from the `PlotLegends` package

```
Legend::usage = "\!\(\*RowBox[{\"Legend\", \"[\", RowBox[{RowBox[{\"{\", RowBox[{RowBox[{\"{\", RowBox[{SubscriptBox[StyleBox[\"box\", \"TI\"], StyleBox[\"1\", \"TR\"]], \",\", SubscriptBox[StyleBox[\"text\", \"TI\"], StyleBox[\"1\", \"TR\"]]}], \"}\"}], \",\", StyleBox[\"\[Ellipsis]\", \"TR\"]}], \"}\"}], \",\", StyleBox[\"options\", \"TI\"]}], \"]\"}]\) generates a legend with the specified boxes and text.\n\!\(\*RowBox[{\"Legend\", \"[\", RowBox[{StyleBox[\"func\", \"TI\"], \",\", StyleBox[\"num\", \"TI\"], \",\", StyleBox[\"options\", \"TI\"]}], \"]\"}]\) generates a legend by applying \!\(\*StyleBox[\"func\", \"TI\"]\) to numbers between 0 and 1, incremented by the number of boxes \!\(\*RowBox[{StyleBox[\"num\", \"TI\"], \"-\", \"1\"}]\).\n\!\(\*RowBox[{\"Legend\", \"[\", RowBox[{StyleBox[\"func\", \"TI\"], \",\", StyleBox[\"num\", \"TI\"], \",\", StyleBox[\"mintext\", \"TI\"], \",\", StyleBox[\"maxtext\", \"TI\"], \",\", StyleBox[\"options\", \"TI\"]}], \"]\"}]\) labels the first and last boxes with \!\(\*StyleBox[\"mintext\", \"TI\"]\) and \!\(\*StyleBox[\"maxtext\", \"TI\"]\) respectively."
```

If you want such usage messages in your code, I suggest you put them in a separate `.m` file like it is done for many packages. This specific `.m` file could be edited with the front end and then you can (a) typeset this stuff easily and (b) you never have to look at this in raw form.

I'm not sure how much you follow the (currently stalled) development, but we have many many open suggestions that will have, as @szhorvat pointed out, a greater impact than supporting subscripts. Look at [the trello board here](https://trello.com/b/qnblZBJi/mathematica-intellij-idea-plugin-roadmap).
