### ISSUE TITLE
Complete support for named slots

### ISSUE THREAD

**Issue by halirutan** [halirutan/Mathematica-IntelliJ-Plugin#34]
Currently, only this kind of named-slots are supported: `#name`
I knew that there was another form like `#["name"]` that is still not included into the plugin, but apparently even the form `#"name"` is valid. See this discussion on [stackexchange](http://mathematica.stackexchange.com/questions/68870/did-10-0-2-break-some-forms-for-named-slots) for more information.

**Comment by halirutan** [comment]
Fixed in current version 1.3.5

**Comment by szhorvat** [comment]
`#name` and `#"name"` are equivalent.  The latter form is to allow for spaces and other non-alphanumeric characters in the slot name.

But `#["name"]` is something different.

See their FullForms.

**Comment by halirutan** [comment]
I know that their `FullForm` is different, but is there any practical relevance where it is important whether I use the `#"Test"` or `#["Test"]`?

I know that the `#Test` has obvious restrictions because `Test` needs to be a valid identifier.

**Comment by szhorvat** [comment]
Sorry, I shouldn't respond when I'm so tired.  I understand your point now.

**Comment by szhorvat** [comment]
One practical difference is what happens when the association we pass to the function doesn't have the requested key.

![image](https://cloud.githubusercontent.com/assets/1212871/14452582/e44420f8-008f-11e6-9844-45b53ad53394.png)

**Comment by halirutan** [comment]
OK. For our purpose in the plugin, it is important that I recognize the slots as slots to make referencing possible. The evaluation behavior shouldn't concern us at this moment.
