### ISSUE TITLE
Move to the definition (Workbench's F3)

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Mathematica-IntelliJ-Plugin#48]
I think it is useful to have a shortcut for doing this:

having selected a symbol, or a cursor inside/right after, move to the line where the first definition of that symbol is found.
- the definition can be in **different file** from the project,
- when selected e.g. ``Context`symbol``, or right after, it doesn't need to be able to find a definition which isn't using a full name (e.g. `symbol[x_]:=x^2`), it is a user's duty to select only a `symbol` before search (that's how it is done in WB, probably because it was faster to implement)

It is done with F3 in Workbench.

**Comment by szhorvat** [comment]
There's this:

https://www.jetbrains.com/help/idea/2016.3/navigating-to-declaration-or-type-declaration-of-a-symbol.html

It goes to the first occurrence, which may be the usage message.

**Comment by halirutan** [comment]
I think you will be delighted to hear, that I have started a "goto related" handler that can be called on every global symbol and gives you instantly a dialog from which you can choose where you want to navigate

![gototarget](https://cloud.githubusercontent.com/assets/511683/21513087/cab946da-ccb4-11e6-9ba3-141bf039e8d3.png)

**Comment by halirutan** [comment]
Version 3 of the plugin contains several functions for this

1. `Navigate -> Declaration (Ctrl + B)` that shows you places where a symbol is assigned a value (DownValue, OwnValue, SyntaxInformation)
2. `Navigate -> Related Symbol (Ctrl + Alt + Home)` that shows you all *usages* of a symbol in the file
3. `Edit -> Find -> Find Usages (Alt + F7)` that shows you all usages of a symbol across the project in a separate window
