### ISSUE TITLE
Suggestion: Add support for MathLink/WSTP .tm files

### ISSUE THREAD

**Issue by Masterxilo** [halirutan/Mathematica-IntelliJ-Plugin#50]
.tm files are processed by 

```
"C:\Program Files\Wolfram Research\Mathematica\10.4\SystemFiles\Links\WSTP\DeveloperKit\Windows-x86-64\CompilerAdditions\mldev64\bin\wsprep.exe"
```

or 

```
"C:\Program Files\Wolfram Research\Mathematica\10.4\SystemFiles\Links\MathLink\DeveloperKit\Windows-x86-64\CompilerAdditions\mldev64\bin\mprep.exe"
```

to produce .c code necessary to build an application that can be `Install[]`ed as an external program.

Here's an example of mine:

```
:Evaluate: BeginPackage["InfiniTAM`"]

:Evaluate: << numerics`;
    poseMatrixQ[x_] := numericMatrixQ[x, {4, 4}];
    IntrinsicsPattern[] := {fx_?NumericQ, fy_?NumericQ, cx_?NumericQ, cy_?NumericQ, w_Integer, h_Integer};
    NamelessIntrinsicsPattern[] := {_?NumericQ, _?NumericQ, _?NumericQ, _?NumericQ, _Integer, _Integer};

:Begin:
:Function:       createScene
:Pattern:        createScene[voxelSize_Real]
:Arguments:      { voxelSize }
:ArgumentTypes:  { Real }
:ReturnType:     Integer
:End:

:Evaluate: EndPackage[]
```

It would be nice if the plugin recognized these files (basically just the tags) and could act accordingly.
Even just highlighting/autocompleting the keywords and not counting them as syntax errors would be enough, it doesn't need to recognize that after `:Function:` there should be a C identifier.

Reference

https://reference.wolfram.com/language/tutorial/WSTPDeveloperGuide-Windows.html
https://reference.wolfram.com/language/ref/file/file.tm.html
https://reference.wolfram.com/language/tutorial/SettingUpExternalFunctionsToBeCalledFromTheWolframLanguage.html

See  

```
C:\Program Files\Wolfram Research\Mathematica\10.4\SystemFiles\Links\MathLink\DeveloperKit\Windows-x86-64\MathLinkExamples
```

or

```
C:\Program Files\Wolfram Research\Mathematica\10.4\SystemFiles\Links\WSTP\DeveloperKit\Windows-x86-64\WSTPExamples
```

 subfolders for some examples.

**Comment by halirutan** [comment]
I gave this some thought. What is needed here is something different: Basically, `.tm` files are c-files. So you would need CLion to highlight them properly. *There* you could use IDEA feature of injecting a different language into this file and mark a region as Mathematica code.

This won't work out of the box and it is way too much trouble to implement this when only a handful of people would use it.
