### ISSUE TITLE
Improvement of syntax highlighting for full names of symbols inside scoping constructs

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Mathematica-IntelliJ-Plugin#52]
![image](https://cloud.githubusercontent.com/assets/15227576/17619294/a56021f2-6084-11e6-87b7-6fe75d375e68.png)

I'd expect Test`x to not be green. Nothing major, just reporting.

**Comment by halirutan** [comment]
@kubaPod I have almost reworked everything and this should be fixed now. The thing is, that this fix required changes in almost every place where the (possibly implicit) context and the name of a symbol are used. This includes

* resolving of definitions and usages of symbols
* code completion for globally and locally defined symbols
* highlighting of built-in, global and local symbols
* annotators (like the Wrong Version Annotator) that need to know symbol names

When I include this into one of the next builts, I need you to pay attention if something is broken! Anyway, it should work now as expected

![sshot](http://i.imgur.com/1vZBbXy.png)
![screenshot1](http://i.imgur.com/ZVJYfAg.png)
![sshot](http://i.imgur.com/Y4nGZSu.png)

Tip: If you want to complete such variables, please remember that you can shorten the context. Therefore, you can type ``G`x`` to complete those variables.
