### ISSUE TITLE
Wrapping behavior on paste

### ISSUE THREAD

**Issue by rgatkinson** [halirutan/Mathematica-IntelliJ-Plugin#56]
When I paste in code from elsewhere (such as an existing .nb) into a .m I'm editing in Idea, it always seems to word-wrap (at 80 columns, I think).

Is there some way to disable this behavior, or, at least, to set the wrapping threshold to something much larger?

**Comment by halirutan** [comment]
Is my assumption correct that by *from elsewhere* you mean *from Mathematica*? If yes, can you please try to use <kbd>Strg</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd> or the context menu "Copy As" -> "Plaintext" to copy the code?

Does this solve the problem? Btw, it has nothing to do with IDEA.

**Comment by rgatkinson** [comment]
Thanks. Copy As / PlainText demonstrates that the problem is indeed on the copying side, not the pasting side.
