### ISSUE TITLE
Enhancement: code folding for sections

### ISSUE THREAD

**Issue by simonkeys** [halirutan/Mathematica-IntelliJ-Plugin#57]
It would be great if code folding were supported for the standard section, subsection, etc comments:

```
(* ::Section:: *)
(*section title*)
...code...
(* ::Section:: *)
(*section title*)
```

Or it might require adding an "end section" comment, like this? 

```
(* ::Section:: *)
(*section title*)
...code...
(* ::End Section:: *)
(* ::Section:: *)
(*section title*)
```

Failing that, is there a way to get the built-in custom folding regions, e.g.,

```
//region Description
...
//endregion
```

to work in a Mathematica package file?

**Comment by halirutan** [comment]
If have implemented the first version of this. There is no need for an `(* ::End Section:: *)`. I guess I can make it consistent with completely valid syntax. As soon as I have finished it I'll report back.
