### ISSUE TITLE
Refactoring is broken

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#60]
I have 2.0.11.  There is something wrong with symbol renaming.  While editing the name of a symbol, it updates all occurrences. But after pressing Enter to finalize the edit, only a single occurrance of the name changes.  The rest reverts to the original form.

Here's a screen recording:

![untitled3](https://cloud.githubusercontent.com/assets/1212871/21293433/9ddea098-c524-11e6-8581-e4db2a52e3c5.gif)

**Comment by halirutan** [comment]
This is unfortunate. I'll look into it. Can you provide this small snip of code for testing, because I don't see the issue on my machine.

**Comment by szhorvat** [comment]
Try a symbol with `$`.  Put this at the top level of a file and rename `$foo`.  Can you reproduce it like this?

```
$foo

fun[] := 
    Module[{},
      $foo = xyz;
      $foo = 2*$foo
    ]
```

**Comment by halirutan** [comment]
This is a bug in Idea. I have hacked around this issue and it should work in one of the next releases

**Comment by szhorvat** [comment]
It seems the problem is still there in 2.0.13, but I suggest we just wait for Idea to fix the underlying cause.

Do you have an insight into when renaming is unreliable?  Is it only when there is a `$` in the name?

![image](https://cloud.githubusercontent.com/assets/1212871/21518639/9940b548-ccf0-11e6-9c60-69ce15a03ef3.png)

![renaming](https://cloud.githubusercontent.com/assets/1212871/21518658/ba80281a-ccf0-11e6-82af-f25a9abdb71c.gif)

It doesn't show in the screen recording, but I used right click -> Refactor -> Rename...

**Comment by halirutan** [comment]
No it works, I just haven't included it in this built. I'm sorry for the confusion.

**Comment by szhorvat** [comment]
Great! :-)  Thank you.  I didn't hope for much after you said that it was an Idea bug.

**Comment by halirutan** [comment]
A new built is coming shortly when Travis has finished. Please try this one.

**Comment by szhorvat** [comment]
It works fine in 2.0.14.
