### ISSUE TITLE
If and Switch statements are not "collapsible".

### ISSUE THREAD

**Issue by kkkmail** [halirutan/Mathematica-IntelliJ-Plugin#66]
The header speaks for itself. 

A statement like:
```
  If[x == 1,
    (
      y = 1;
    ),
    (
      y = 2;
    )
  ];
```

cannot be collapsed (like `Do` or a function declaration, for example). The same, of course, applies to `If` within `If` and to `Switch` statement.

NOTE: While the brackets and semicolons are not needed in that particular example, they become important in a multi-line statement. In addition, plug-in is "unhappy" about missing last semicolon even when Mathematica is "happy" about it.

**Comment by halirutan** [comment]
Yes, you are correct. In the current implementation, only *scoping constructs* are foldable. The folding engine is basically able to fold all function calls, but this might become more unnerving than it helps. Be problem is, that you fold a region with `Ctrl`+`.`. Now assume you are inside a deeply nested expression (which is the common case in Mathematica, even if you don't see it instantly). If you new press "close region" then it doesn't now, what you want to close and at the worst case, it starts to fold regions from inner to outer. I am not sure this is a good idea. Therefore, the decision was to fold only the following things (you find the enum of foldable things [here](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/blob/934d6f610e8686df8e6ce00d38282087a23a5616/src/de/halirutan/mathematica/parsing/psi/util/LocalizationConstruct.java#L115-L115) in source):

```
public enum ConstructType {
    MODULE, BLOCK, WITH, FUNCTION, DYNAMICMODULE, TABLE, DO, SUM, NULL, INTEGRATE, NSUM, PLOT, PLOT3D, CONTOURPLOT, CONTOURPLOT3D,
    LIMIT, RULEDELAYED, SETDELAYEDPATTERN, MANIPULATE, COMPILE, ANONYMOUSFUNCTION, PARAMETRICPLOT, PARAMETRICPLOT3D;
```

Except for `NULL`, all these things should be foldable. This gives you the ability to fold definitions and longer modules, tables, etc.. If it is really wished, to extend this list, then this is certainly possible. In that case, I would like you to create a card on the [Trello board](https://trello.com/b/qnblZBJi/mathematica-intellij-idea-plugin-roadmap) here and if it gets some upvotes, I'm happy to include it in the next release. Please state clearly what you think would be helpful.

Sidenote about

> In addition, plug-in is "unhappy" about missing last semicolon even when Mathematica is "happy" about it.

This is an annotator and you can simply turn it off if you like. For information on how to do this please read my article [here](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/wiki/Code-Inspections). The reason why I implemented it is that _I personally_ like a consistent style and the common convention to don't do it in `.m` files make it that packages are not a correct Mathematica expression. Of course, it works and almost everyone leaves them out. It's a matter of taste.

**Comment by kkkmail** [comment]
Thanks for comments. I am not much concerned about the last semicolon, of course, as I attempt to always put them. 

In regards to `If` and other foldable structures: technically any Mathematica expression is a list with the head. If is not an exclusion. It starts with "[" and ends with matching "]". So, I would say that any expression in the form: 

`<SomeHead>[<SomeContent>]`

or, in general:

`<SomeHead><OpeningBracket><SomeContent><MatchingClosingBracket>`

should be foldable. The same goes with opening "(", closing ")" and, I guess, should also apply to opening "[[", closing "]]" and opening "{", closing "}". After all the code is able to reformat correctly all `If` statements (with any of these constructions) with the exception of the issue described in https://github.com/halirutan/Mathematica-IntelliJ-Plugin/issues/65 . I will create a card on Trello board as you suggested.

**Comment by halirutan** [comment]
I created the trello card for you.
