### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by sumanban** [halirutan/Mathematica-IntelliJ-Plugin#84]
I could create a new file but how to run it?

**Comment by szhorvat** [comment]
You run it from within Mathematica.  In a typical workflow you have both Mathematica and the IDE open.  You edit a package in the IDE, re-load it in Mathematica, then test it.

**Comment by halirutan** [comment]
[Point number 3 in the FAQ](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/wiki/FAQ).
