### ISSUE TITLE
"Surround with" in Python files stops working with active MMA-IntelleJ pulgin

### ISSUE THREAD

**Issue by olejorik** [halirutan/Mathematica-IntelliJ-Plugin#85]
I have just installed the plugin in PyCharm (CE, 2017.2.3) and I have discovered that "Surround With..." has stopped to work in Python files (it works OK in MMA files). If I deactivate the plugin, it works again. 

Here's the screenshot:
![image](https://user-images.githubusercontent.com/12269930/30441728-8c4f92b2-997a-11e7-9cd6-eea9631a3865.png)

**Comment by adil-hussain-84** [comment]
This plugin also affects Java files. Disabling this plugin gets IntelliJ's "Surround with" feature working again.

**Comment by halirutan** [comment]
I have this issue on my radar. I'm not exactly sure why this happens because the plugin's surrounders should only work in Mathematica files, but I will debug this through.
