### ISSUE TITLE
AutoComplete for undefined variables in scoping construct

### ISSUE THREAD

**Issue by eduardoofthehour** [halirutan/Mathematica-IntelliJ-Plugin#87]
I would like to be able to autocomplete undefined variables in scoping constructs. 

e.g in Block[{}, foo = bar]
I would like to be able to autocomplete in the list in the first argument

**Comment by halirutan** [comment]
There is an *intention* in the development version for this that I have to debug and polish but does basically what you want. It basically lets you press `Alt+Enter` on the `foo` symbol and suggests to move this variable to the definition list.

**Comment by eduardoofthehour** [comment]
Great! Thank you

**Comment by halirutan** [comment]
Should work now. When you are near the undefined symbol, a light-bulb appears and pressing `Alt`+`Enter` lets you push this symbol to the definition list.

![block](https://user-images.githubusercontent.com/511683/53677278-aa8eba00-3cad-11e9-8e30-76a25ea4b420.gif)

**Comment by eduardoofthehour** [comment]
This is amazing thanks
