### ISSUE TITLE
Multiply occurring pattern names in rules

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#91]
I am reporting this "bug" not because it bothers me, but because it may be important to think about.

In practice one may have patterns like 

    {a_,a_} :> a+c

Only the first `a` is highlighted instead of both.

![image](https://user-images.githubusercontent.com/1212871/31555273-b07969a6-b040-11e7-8f19-5abfd903124b.png)

Another example:

    f[a_] | g[a_] :> a

![image](https://user-images.githubusercontent.com/1212871/31555477-7065f68a-b041-11e7-8353-83b93c7adbec.png)

(Unlike the first example, IMO a replacement rule like this is extremely weird, but it is both allowed and found in the wild. If you're wondering what happens with `1 /. 1 | a_ :> a`: it returns `Sequence[]`)

**Comment by halirutan** [comment]
Damn, I had this fixed on some branch. Need to look at it again.

**Comment by halirutan** [comment]
@szhorvat OK, this took a whole night and was only one line of code, but I had to debug through a large portion of the IntelliJ API to understand what happens. This should work now and many similar cases too. I even had to a new action that shows which symbol references to which other symbol. This action will be available under the **Wolfram Language | Debug** menu and gives for the following situation the output that below (I know the `_` on the rhs is wrong, but it was only a test)

![image](https://user-images.githubusercontent.com/511683/63198877-6edd8600-c07c-11e9-9117-df9edb788dba.png)


```
"myVar" at offset 1 -> "myVar" at offset 1 (is Ref: true, soft: false)
"myVar" at offset 11 -> "myVar" at offset 1 (is Ref: true, soft: false)
"myVar" at offset 20 -> "myVar" at offset 1 (is Ref: true, soft: false)
"f" at offset 27 -> "null" at offset -1 (is Ref: true, soft: false)
"a" at offset 29 -> "a" at offset 29 (is Ref: true, soft: false)
"g" at offset 35 -> "null" at offset -1 (is Ref: true, soft: false)
"a" at offset 37 -> "a" at offset 29 (is Ref: true, soft: false)
"a" at offset 44 -> "a" at offset 29 (is Ref: true, soft: false)
```

As you can see, all `myVar` variables and patterns refer to the first `myVar_` instance. This is correct and it was like this before, but something else was wrong. Now, highlighting and renaming should work as expected and if possible, I would like you to watch out for strange things regarding such things. I hope I didn't break something else.
